# Generated by Django 2.2.6 on 2019-11-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Name', max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('addressL1', models.CharField(blank=True, max_length=300)),
                ('addressL2', models.CharField(blank=True, max_length=200)),
                ('addressL3', models.CharField(blank=True, max_length=100)),
                ('coins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profiles',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
