# Generated by Django 2.2.6 on 2019-11-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20191113_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='application',
            name='applicationID',
            field=models.CharField(max_length=20, verbose_name='Application ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Recieved', 'Recieved'), ('Confirmed', 'Confirmed')], default='Applied', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vehicleNumber',
            field=models.CharField(max_length=100, verbose_name='Vehicle Number'),
        ),
    ]
