# Generated by Django 2.2.6 on 2019-11-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20191113_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='servicePhotos'),
            preserve_default=False,
        ),
    ]
