# Generated by Django 2.2.6 on 2019-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(default=1, upload_to='CarBrands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='CarModel'),
            preserve_default=False,
        ),
    ]
